language: node_js
node_js: '8'
cache:
  directories:
  - node_modules
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
before_install:
- npm i -g npm5@latest
script:
- VERSION=0.0.0-development ENVIRONMENT=production BASE_HREF=/pictureframe/ make demo
- npm run lint
- npm run test
after_success:
- |
  cd build
  git init
  git config user.name "Travis CI"
  git config user.email "m@coderbyheart.com"
  git add .
  git commit -m "Deploy to GitHub Pages"
  git push --force --quiet "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" master:gh-pages > /dev/null 2>&1
